[package]
name = "bevy_ecs_tilemap"
description = "A tilemap rendering plugin for bevy which is more ECS friendly by having an entity per tile."
version = "0.4.0"
authors = ["John Mitchell"]
homepage = "https://github.com/StarArawn/bevy_ecs_tilemap"
repository = "https://github.com/StarArawn/bevy_ecs_tilemap"
license-file = "LICENSE"
edition = "2018"
exclude = ["assets/*", "screenshots/*"]

[workspace]
members = ["./", "tools/ci"]

[features]
default = []

[dependencies]
bevy = { version = "0.5", default-features = false }
morton-encoding = "2.0"
log = "0.4"

[dev-dependencies]
anyhow = { version = "1.0" }
bevy = { version = "0.5", default-features = true }
ldtk_rust = { version = "0.5"}
rand = "0.8"
env_logger = "0.9"
serde_json = { version = "1.0"}
tiled = { version = "0.9", default-features = false }
